GET http://localhost:3000/users

### Requête POST
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Marc Vinicius",
  "username": "developerMarc",
  "email": "marc@example.com",
  "password": "0123456",
  "avatar": "https://exemple.com/avatar.jpg",
  "background": "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

### Requête GET by id
GET http://localhost:3000/users/68c86adeca01773ac218440b

### Requête PATCH (mise à jour partielle)
PATCH http://localhost:3000/users/68c86adeca01773ac218440b
Content-Type: application/json

{
  "name": "Jane Doe",
  "background": "vert"
}

### requete POST login
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "marc@example.com",
  "password": "0123456"
}

### requete Get news
GET http://localhost:3000/news

### requete Get news TOP
GET http://localhost:3000/news/top

### requete Get news By Id
GET http://localhost:3000/news/68f1435c0a4d4d370566ce32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yzg2ZjM2MzU1NTU1YmI1OWEwN2M4NyIsImlhdCI6MTc2MDkwMTEzMywiZXhwIjoxNzYwOTg3NTMzfQ.akIng2J7JH7a79hnS-5HBn8q-FM9zFCD8vzCcf6S1OA

### requete Get news By Title Query
GET http://localhost:3000/news/search?title=updated

### requete Get news By User
GET http://localhost:3000/news/byUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yzg2ZjM2MzU1NTU1YmI1OWEwN2M4NyIsImlhdCI6MTc2MDkwMTEzMywiZXhwIjoxNzYwOTg3NTMzfQ.akIng2J7JH7a79hnS-5HBn8q-FM9zFCD8vzCcf6S1OA


### requete Get news variables
GET http://localhost:3000/news?limit=5&offset=35

### requete POST news
POST http://localhost:3000/news
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yzg2ZjM2MzU1NTU1YmI1OWEwN2M4NyIsImlhdCI6MTc2MDkwMTEzMywiZXhwIjoxNzYwOTg3NTMzfQ.akIng2J7JH7a79hnS-5HBn8q-FM9zFCD8vzCcf6S1OA

{
  "title": "Search",
  "text": "Ceci est mon text pour test",
  "banner": "imageTest.jpg"
}


### requete POST news
PATCH http://localhost:3000/news/68f1435c0a4d4d370566ce32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yzg2ZjM2MzU1NTU1YmI1OWEwN2M4NyIsImlhdCI6MTc2MDkwMTEzMywiZXhwIjoxNzYwOTg3NTMzfQ.akIng2J7JH7a79hnS-5HBn8q-FM9zFCD8vzCcf6S1OA

{
  "title": "Updated 3",
  "text": "Ceci est mon text pour test",
  "banner": "imageTest.jpg"
}

### requete Get news By Id
DELETE http://localhost:3000/news/68f1435c0a4d4d370566ce32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yzg2ZjM2MzU1NTU1YmI1OWEwN2M4NyIsImlhdCI6MTc2MDkwMTEzMywiZXhwIjoxNzYwOTg3NTMzfQ.akIng2J7JH7a79hnS-5HBn8q-FM9zFCD8vzCcf6S1OA



